/** Shared PostSoma behavior vocabulary with Kitchen-only working accessories. */
export const mascotConfig = {
  version: "3.0.0-kitchen",
  storageKey: "postsoma-kitchen-mascot-v3",
  core: {
    light: "/mascot/core/plate_light.png",
    width: 1122,
    height: 1228,
    sprout: {
      light: "/mascot/core/sprout_light.png",
      width: 135,
      height: 137,
      left: "43.94%",
      top: "0%",
      displayWidth: "12.03%",
      displayHeight: "11.16%",
      pivot: "48.74% 85.4%",
    },
    eyes: [
      { x: 728.9, y: 563.8, moonRadius: 48.6, haloRadius: 66 },
      { x: 382.7, y: 563.9, moonRadius: 48.6, haloRadius: 66 },
    ],
  },
  slots: {
    hat: { src: "/mascot/skins/recipe/hat_clean.png", left: "23%", top: "-9%", width: "30%", pivot: "50% 90%" },
    spatula: { src: "/mascot/skins/recipe/spatula_clean.png", right: "0%", top: "30%", width: "22%", pivot: "50% 90%" },
  },
  behaviorWheel: [
    { id: "sprout_sway", weight: 40, durationMs: 3_500 },
    { id: "peek_curious", weight: 30, durationMs: 1_800 },
    { id: "wander_slide", weight: 20, durationMs: 4_500 },
    { id: "subtle_tilt", weight: 10, durationMs: 1_200 },
  ],
  scheduler: {
    tickMs: 100,
    heartbeatMs: 1_000,
    durationDrift: 0.2,
    firstActionMs: 4_500,
    idleGapMinMs: 1_400,
    idleGapMaxMs: 2_800,
    tapWindowMs: 320,
    activeIdleMs: 10_000,
    sleepAfterMs: 90_000,
    hoverMs: 560,
    clickMs: 760,
    flinchMs: 480,
    blushMs: 980,
    shyHideMs: 650,
    shyHiddenMs: 2_400,
    shyQuietMs: 2_000,
    cookingMs: 2_100,
    hatOnlyMs: 2_500,
    anticCooldownMs: 20_000,
    alertMs: 900,
    scrollThresholdPx: 360,
    rapidPointerSpeedPxPerSecond: 900,
    nearbyRadiusPx: 150,
    minimumAlertGapMs: 1_800,
  },
  motion: {
    stage: { mobile: { width: 108, height: 120 }, desktop: { width: 122, height: 135 } },
    restOffsetPx: { mobile: 60, desktop: 68 },
    peekOffsetPx: { mobile: 46, desktop: 54 },
    hatOnlyOffsetPx: { mobile: 99, desktop: 111 },
    hiddenOffsetPx: { mobile: 140, desktop: 155 },
    companionBottom: "0px",
    minHorizontalPercent: 16,
    maxHorizontalPercent: 84,
    startHorizontalPercent: 78,
    wanderMinPercent: 16,
    wanderMaxPercent: 84,
    wanderMinStepPercent: 16,
    wanderMaxStepPercent: 32,
  },
  drives: {
    defaults: { energy: 80, curiosity: 60, affection: 40 },
    energyDecayPerMinute: 1.5,
    curiosityDecayPerMinute: 2,
    affectionDecayPerMinute: 1,
    sleepRecoveryPerMinute: 10,
    hoverAffection: 8,
    clickAffection: 15,
    nearbyCuriosity: 10,
  },
  priorities: { autonomous: 0, environment: 1, direct: 2 },
} as const;

export type MascotBehaviorId = (typeof mascotConfig.behaviorWheel)[number]["id"];
export type MascotPriority = (typeof mascotConfig.priorities)[keyof typeof mascotConfig.priorities];

export default mascotConfig;
